project:
  type: website
  output-dir: docs

website:
  title: "Afsar Chowdhury"
  favicon: images/rzf.ico
  site-url: https://afsarchowdhury.github.io/
  description: "The musings of a rambler"
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Alert** Updated to Quarto on 05/01/2025.  Some funtionality may be lost."
  #   type: primary
  #   position: below-navbar
  navbar:
    logo: images/rzf.ico
    right:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html
      - icon: github
        href: https://github.com/afsarchowdhury
      - icon: envelope
        href: mailto:afsarchowdhury@proton.me
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      dark: solar
      light: minty
    css: styles.css

editor: source

